#!/bin/bash

# Build script for genj
# Compiles in release mode, creates template ZIPs, and generates Debian package

set -e

echo "🔨 Building genj in release mode with ZIP package..."

# Compile in release mode
echo "🚀 Compiling..."
cargo build --release
echo "✓ Compilation successful"

# Generate ZIP archives for each template
echo "📦 Generating template ZIPs..."
TEMPLATE_SRC_DIR="templates"
TEMPLATE_ZIP_DIR="target/release-templates"
mkdir -p "$TEMPLATE_ZIP_DIR"


# Utilise le binaire Rust zip-template pour zipper chaque template
for dir in "$TEMPLATE_SRC_DIR"/*/; do
    template_name=$(basename "$dir")
    zip_file="$TEMPLATE_ZIP_DIR/${template_name}.zip"
    echo "  - $template_name -> $zip_file"
    cargo run --release --bin zip-template -- "$dir" "$zip_file"
done

echo "✓ Template ZIPs generated in $TEMPLATE_ZIP_DIR"

# Execute package creation binary (optional)
if [ -f "src/bin/build-package.rs" ] || [ -f "src/bin/build-package/main.rs" ]; then
    echo "📦 Creating ZIP package (build-package binary)..."
    cargo run --release --bin build-package
    echo "✨ ZIP package generated by build-package binary"
fi

# On Linux, run Debian package creation script if present
OS_NAME="$(uname -s)"
if [ "$OS_NAME" = "Linux" ]; then
    if [ -x ./build_deb.sh ]; then
        echo "📦 Creating .deb package (Linux)..."
        # Pass template ZIP directory to build_deb.sh
        TEMPLATE_INSTALL_DIR="usr/share/genj/templates"
        export GENJ_TEMPLATE_ZIP_DIR="$TEMPLATE_ZIP_DIR"
        export GENJ_TEMPLATE_INSTALL_DIR="$TEMPLATE_INSTALL_DIR"
        ./build_deb.sh
        echo "✅ .deb package created successfully"
        echo "Template ZIPs will be installed in /$TEMPLATE_INSTALL_DIR"
        echo "Default search path for templates: /$TEMPLATE_INSTALL_DIR"
        echo "You can also store your own templates in ~/.genj/ in your home directory."
    else
        echo "⚠️  build_deb.sh not found or not executable — skipping .deb creation"
    fi
else
    echo "ℹ️  Detected system: $OS_NAME — .deb creation only on Linux."
fi
